
[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/ojrac/opensimplex-go"
  version = "1.0.1"

[[constraint]]
  name = "gonum.org/v1/gonum"
  branch = "master"

[[constraint]]
  name = "github.com/tdewolff/minify"
  version = "2.3.8"